[2025-08-20 12:05:38,171: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 2.0 seconds...
[2025-08-20 12:05:45,006: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 4.0 seconds...
[2025-08-20 12:05:53,063: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 6.0 seconds...
[2025-08-20 12:06:03,089: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 8.0 seconds...
[2025-08-20 12:06:15,133: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 10.0 seconds...
[2025-08-20 12:06:29,150: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 12.0 seconds...
[2025-08-20 12:06:45,171: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 14.0 seconds...
[2025-08-20 12:07:03,189: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 16.0 seconds...
[2025-08-20 12:07:23,215: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 18.0 seconds...
[2025-08-20 12:07:45,241: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 20.0 seconds...
[2025-08-20 12:08:09,265: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 22.0 seconds...
[2025-08-20 12:08:35,293: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 24.0 seconds...
[2025-08-20 12:09:03,332: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 26.0 seconds...
[2025-08-20 12:09:33,369: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 28.0 seconds...
[2025-08-20 12:10:05,409: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 30.0 seconds...
[2025-08-20 12:10:39,450: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:11:15,489: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:11:51,528: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:12:27,581: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:13:03,614: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:13:39,660: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:14:15,699: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:14:51,724: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:15:27,755: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:16:03,785: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:16:39,821: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:17:15,857: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:17:51,888: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:18:27,918: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:19:03,965: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:19:40,004: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:20:16,127: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:20:52,240: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:21:28,357: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:22:04,469: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:22:40,546: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:23:16,637: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:23:52,750: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:24:28,859: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:25:04,978: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:25:41,079: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:26:17,147: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:26:53,250: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:27:29,358: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:28:05,498: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:28:41,616: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:29:17,718: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:29:53,801: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:30:29,882: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:31:05,995: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:31:42,101: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:32:18,183: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:32:54,297: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:33:30,418: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:34:06,525: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:34:42,626: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:35:18,744: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:35:54,835: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:36:30,942: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:37:07,040: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:37:43,152: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:38:19,263: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:38:55,359: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:39:31,464: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:40:07,556: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:40:43,616: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:41:19,724: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:41:55,845: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:42:31,944: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:43:08,043: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:43:44,165: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:44:20,287: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:44:56,402: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:45:32,540: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:46:08,657: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:46:44,772: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:47:20,883: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:47:56,977: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:48:33,074: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:49:09,177: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:49:45,262: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:50:21,373: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:50:57,473: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:51:33,589: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:52:09,704: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:52:45,830: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:53:21,919: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:53:58,023: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:54:34,135: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:55:10,249: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:55:46,352: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:56:22,464: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:56:58,549: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:57:34,652: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:58:10,753: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:58:46,887: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:59:22,990: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 12:59:59,036: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 13:00:35,084: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 13:01:11,121: ERROR/MainProcess] beat: Connection error: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.. Trying again in 32.0 seconds...
[2025-08-20 13:01:47,178: CRITICAL/MainProcess] beat raised exception <class 'kombu.exceptions.OperationalError'>: OperationalError('Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.')
Traceback (most recent call last):
  File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\kombu\transport\virtual\base.py", line 951, in create_channel
    return self._avail_channels.pop()
           ~~~~~~~~~~~~~~~~~~~~~~~~^^
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\redis\connection.py", line 389, in connect_check_health
    sock = self.retry.call_with_retry(
        lambda: self._connect(), lambda error: self.disconnect(error)
    )
  File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\redis\retry.py", line 105, in call_with_retry
    return do()
  File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\redis\connection.py", line 390, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ~~~~~~~~~~~~~^^
  File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\redis\connection.py", line 803, in _connect
    raise err
  File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\redis\connection.py", line 787, in _connect
    sock.connect(socket_address)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\kombu\connection.py", line 472, in _reraise_as_library_errors
    yield
  File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\kombu\connection.py", line 459, in _ensure_connection
    return retry_over_time(
        self._connection_factory, self.recoverable_connection_errors,
    ...<2 lines>...
        callback, timeout=timeout
    )
  File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\kombu\utils\functional.py", line 318, in retry_over_time
    return fun(*args, **kwargs)
  File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\kombu\connection.py", line 938, in _connection_factory
    self._connection = self._establish_connection()
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\kombu\connection.py", line 860, in _establish_connection
    conn = self.transport.establish_connection()
  File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\kombu\transport\virtual\base.py", line 975, in establish_connection
    self._avail_channels.append(self.create_channel(self))
                                ~~~~~~~~~~~~~~~~~~~^^^^^^
  File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\kombu\transport\virtual\base.py", line 953, in create_channel
    channel = self.Channel(connection)
  File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\kombu\transport\redis.py", line 751, in __init__
    self.client.ping()
    ~~~~~~~~~~~~~~~~^^
  File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\redis\commands\core.py", line 1219, in ping
    return self.execute_command("PING", **kwargs)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\redis\client.py", line 621, in execute_command
    return self._execute_command(*args, **options)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\redis\client.py", line 627, in _execute_command
    conn = self.connection or pool.get_connection()
                              ~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\redis\utils.py", line 195, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\redis\connection.py", line 1533, in get_connection
    connection.connect()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\redis\connection.py", line 380, in connect
    self.connect_check_health(check_health=True)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\redis\connection.py", line 397, in connect_check_health
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\celery\apps\beat.py", line 113, in start_scheduler
    service.start()
    ~~~~~~~~~~~~~^^
  File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\celery\beat.py", line 644, in start
    interval = self.scheduler.tick()
  File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\celery\beat.py", line 354, in tick
    self.apply_entry(entry, producer=self.producer)
                                     ^^^^^^^^^^^^^
  File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\kombu\utils\objects.py", line 40, in __get__
    return super().__get__(instance, owner)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Python313\Lib\functools.py", line 1042, in __get__
    val = self.func(instance)
  File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\celery\beat.py", line 497, in producer
    return self.Producer(self._ensure_connected(), auto_declare=False)
                         ~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\celery\beat.py", line 480, in _ensure_connected
    return self.connection.ensure_connection(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        _error_handler, self.app.conf.broker_connection_max_retries
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\kombu\connection.py", line 406, in ensure_connection
    self._ensure_connection(*args, **kwargs)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\kombu\connection.py", line 458, in _ensure_connection
    with ctx():
         ~~~^^
  File "C:\Python313\Lib\contextlib.py", line 162, in __exit__
    self.gen.throw(value)
    ~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\kombu\connection.py", line 476, in _reraise_as_library_errors
    raise ConnectionError(str(exc)) from exc
kombu.exceptions.OperationalError: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.
[2025-08-20 13:01:47,216: WARNING/MainProcess] Traceback (most recent call last):
[2025-08-20 13:01:47,216: WARNING/MainProcess]   File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\kombu\transport\virtual\base.py", line 951, in create_channel
    return self._avail_channels.pop()
           ~~~~~~~~~~~~~~~~~~~~~~~~^^
[2025-08-20 13:01:47,216: WARNING/MainProcess] IndexError: pop from empty list
[2025-08-20 13:01:47,217: WARNING/MainProcess] 
During handling of the above exception, another exception occurred:
[2025-08-20 13:01:47,217: WARNING/MainProcess] Traceback (most recent call last):
[2025-08-20 13:01:47,217: WARNING/MainProcess]   File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\redis\connection.py", line 389, in connect_check_health
    sock = self.retry.call_with_retry(
        lambda: self._connect(), lambda error: self.disconnect(error)
    )
[2025-08-20 13:01:47,218: WARNING/MainProcess]   File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\redis\retry.py", line 105, in call_with_retry
    return do()
[2025-08-20 13:01:47,218: WARNING/MainProcess]   File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\redis\connection.py", line 390, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ~~~~~~~~~~~~~^^
[2025-08-20 13:01:47,218: WARNING/MainProcess]   File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\redis\connection.py", line 803, in _connect
    raise err
[2025-08-20 13:01:47,218: WARNING/MainProcess]   File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\redis\connection.py", line 787, in _connect
    sock.connect(socket_address)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^
[2025-08-20 13:01:47,219: WARNING/MainProcess] ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
[2025-08-20 13:01:47,219: WARNING/MainProcess] 
During handling of the above exception, another exception occurred:
[2025-08-20 13:01:47,219: WARNING/MainProcess] Traceback (most recent call last):
[2025-08-20 13:01:47,221: WARNING/MainProcess]   File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\kombu\connection.py", line 472, in _reraise_as_library_errors
    yield
[2025-08-20 13:01:47,222: WARNING/MainProcess]   File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\kombu\connection.py", line 459, in _ensure_connection
    return retry_over_time(
        self._connection_factory, self.recoverable_connection_errors,
    ...<2 lines>...
        callback, timeout=timeout
    )
[2025-08-20 13:01:47,222: WARNING/MainProcess]   File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\kombu\utils\functional.py", line 318, in retry_over_time
    return fun(*args, **kwargs)
[2025-08-20 13:01:47,222: WARNING/MainProcess]   File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\kombu\connection.py", line 938, in _connection_factory
    self._connection = self._establish_connection()
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
[2025-08-20 13:01:47,222: WARNING/MainProcess]   File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\kombu\connection.py", line 860, in _establish_connection
    conn = self.transport.establish_connection()
[2025-08-20 13:01:47,223: WARNING/MainProcess]   File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\kombu\transport\virtual\base.py", line 975, in establish_connection
    self._avail_channels.append(self.create_channel(self))
                                ~~~~~~~~~~~~~~~~~~~^^^^^^
[2025-08-20 13:01:47,223: WARNING/MainProcess]   File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\kombu\transport\virtual\base.py", line 953, in create_channel
    channel = self.Channel(connection)
[2025-08-20 13:01:47,223: WARNING/MainProcess]   File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\kombu\transport\redis.py", line 751, in __init__
    self.client.ping()
    ~~~~~~~~~~~~~~~~^^
[2025-08-20 13:01:47,223: WARNING/MainProcess]   File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\redis\commands\core.py", line 1219, in ping
    return self.execute_command("PING", **kwargs)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
[2025-08-20 13:01:47,224: WARNING/MainProcess]   File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\redis\client.py", line 621, in execute_command
    return self._execute_command(*args, **options)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
[2025-08-20 13:01:47,224: WARNING/MainProcess]   File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\redis\client.py", line 627, in _execute_command
    conn = self.connection or pool.get_connection()
                              ~~~~~~~~~~~~~~~~~~~^^
[2025-08-20 13:01:47,224: WARNING/MainProcess]   File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\redis\utils.py", line 195, in wrapper
    return func(*args, **kwargs)
[2025-08-20 13:01:47,225: WARNING/MainProcess]   File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\redis\connection.py", line 1533, in get_connection
    connection.connect()
    ~~~~~~~~~~~~~~~~~~^^
[2025-08-20 13:01:47,225: WARNING/MainProcess]   File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\redis\connection.py", line 380, in connect
    self.connect_check_health(check_health=True)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
[2025-08-20 13:01:47,225: WARNING/MainProcess]   File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\redis\connection.py", line 397, in connect_check_health
    raise ConnectionError(self._error_message(e))
[2025-08-20 13:01:47,225: WARNING/MainProcess] redis.exceptions.ConnectionError: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.
[2025-08-20 13:01:47,226: WARNING/MainProcess] 
The above exception was the direct cause of the following exception:
[2025-08-20 13:01:47,226: WARNING/MainProcess] Traceback (most recent call last):
[2025-08-20 13:01:47,228: WARNING/MainProcess]   File "<frozen runpy>", line 198, in _run_module_as_main
[2025-08-20 13:01:47,229: WARNING/MainProcess]   File "<frozen runpy>", line 88, in _run_code
[2025-08-20 13:01:47,229: WARNING/MainProcess]   File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Scripts\celery.exe\__main__.py", line 6, in <module>
    sys.exit(main())
             ~~~~^^
[2025-08-20 13:01:47,229: WARNING/MainProcess]   File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\celery\__main__.py", line 15, in main
    sys.exit(_main())
             ~~~~~^^
[2025-08-20 13:01:47,229: WARNING/MainProcess]   File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\celery\bin\celery.py", line 231, in main
    return celery(auto_envvar_prefix="CELERY")
[2025-08-20 13:01:47,230: WARNING/MainProcess]   File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\click\core.py", line 1442, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
[2025-08-20 13:01:47,230: WARNING/MainProcess]   File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\click\core.py", line 1363, in main
    rv = self.invoke(ctx)
[2025-08-20 13:01:47,230: WARNING/MainProcess]   File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\click\core.py", line 1830, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
[2025-08-20 13:01:47,230: WARNING/MainProcess]   File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\click\core.py", line 1226, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-08-20 13:01:47,230: WARNING/MainProcess]   File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\click\core.py", line 794, in invoke
    return callback(*args, **kwargs)
[2025-08-20 13:01:47,231: WARNING/MainProcess]   File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\click\decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
[2025-08-20 13:01:47,231: WARNING/MainProcess]   File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\celery\bin\base.py", line 135, in caller
    return f(ctx, *args, **kwargs)
[2025-08-20 13:01:47,231: WARNING/MainProcess]   File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\celery\bin\beat.py", line 72, in beat
    return beat().run()
           ~~~~~~~~~~^^
[2025-08-20 13:01:47,231: WARNING/MainProcess]   File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\celery\apps\beat.py", line 84, in run
    self.start_scheduler()
    ~~~~~~~~~~~~~~~~~~~~^^
[2025-08-20 13:01:47,231: WARNING/MainProcess]   File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\celery\apps\beat.py", line 113, in start_scheduler
    service.start()
    ~~~~~~~~~~~~~^^
[2025-08-20 13:01:47,232: WARNING/MainProcess]   File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\celery\beat.py", line 644, in start
    interval = self.scheduler.tick()
[2025-08-20 13:01:47,232: WARNING/MainProcess]   File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\celery\beat.py", line 354, in tick
    self.apply_entry(entry, producer=self.producer)
                                     ^^^^^^^^^^^^^
[2025-08-20 13:01:47,232: WARNING/MainProcess]   File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\kombu\utils\objects.py", line 40, in __get__
    return super().__get__(instance, owner)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
[2025-08-20 13:01:47,232: WARNING/MainProcess]   File "C:\Python313\Lib\functools.py", line 1042, in __get__
    val = self.func(instance)
[2025-08-20 13:01:47,232: WARNING/MainProcess]   File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\celery\beat.py", line 497, in producer
    return self.Producer(self._ensure_connected(), auto_declare=False)
                         ~~~~~~~~~~~~~~~~~~~~~~^^
[2025-08-20 13:01:47,232: WARNING/MainProcess]   File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\celery\beat.py", line 480, in _ensure_connected
    return self.connection.ensure_connection(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        _error_handler, self.app.conf.broker_connection_max_retries
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
[2025-08-20 13:01:47,233: WARNING/MainProcess]   File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\kombu\connection.py", line 406, in ensure_connection
    self._ensure_connection(*args, **kwargs)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
[2025-08-20 13:01:47,233: WARNING/MainProcess]   File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\kombu\connection.py", line 458, in _ensure_connection
    with ctx():
         ~~~^^
[2025-08-20 13:01:47,233: WARNING/MainProcess]   File "C:\Python313\Lib\contextlib.py", line 162, in __exit__
    self.gen.throw(value)
    ~~~~~~~~~~~~~~^^^^^^^
[2025-08-20 13:01:47,233: WARNING/MainProcess]   File "C:\Users\itsup\Downloads\FrankTheLocalLLM-main\FrankTheLocalLLM-main\.venv\Lib\site-packages\kombu\connection.py", line 476, in _reraise_as_library_errors
    raise ConnectionError(str(exc)) from exc
[2025-08-20 13:01:47,233: WARNING/MainProcess] kombu.exceptions.OperationalError: Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.
